# Generated by Django 5.0.6 on 2024-06-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
